### ISSUE TITLE
login system

### ISSUE THREAD

**Issue by karma88977** [Zueripat/Currency-Bot#3]
**Is your feature request related to a problem? Please describe.**
n

**Describe the solution you'd like**
das man bevor man das coin system nutzen kann sich einloggen muss das es dann son embed schikt wo man dann klicken kann regristrieren dann schreibt man die daten rein zb email und benutzer name oder so und sollte mann seine daten vergessen ein forgot passwort feature ,um dann sicher zu gehen das er das ist das es dann bei der regristierung eine sicherheits frage gibt oder nhn captcha oder so 

**Describe alternatives you've considered**
  weiteres fällt mir nich ein
**Additional context**

**Comment by Zueripat** [comment]
Guten Tag @karma88977 

Ich verstehe den Sinn hinter einem Login System an solch einer stelle nicht. 
Im Moment kann eh nur der `/getcoins` Command von den Benutzern ohne Admin Rechten benutzt werden und weiter einschränken könnte man es via User direkt oder über Rollen / Channel oder Server. 

Ein pures Login System ohne andere Funktionen würde in diesem Moment nur das benutzten des Bots erschweren. Ebenfalls müsste man zusätzlich Login Daten abspeichern, was dann einfach zusätzlichen Speicher benutzen würde. 

Ich erhoffe mir eine Erklärung des Ziels und würde mich freuen wenn du in Zukunft die richtige Template benutzen würdest.
![image](https://user-images.githubusercontent.com/66902977/202654705-3fc5af28-2ce4-43e8-b686-469493967d13.png)

Mfg @Zueripat
